### ISSUE TITLE
Investigate slow container start on cluster

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-pipeline#100]
This would be a big help

**Comment by lily-mayfield** [comment]
what takes forever

TASK [spark : Start container] ***********************************************************************
task path: /home/lily/OSP/repos/osp-pipeline/deploy/roles/spark/tasks/start.yml:3
META: noop
META: noop
Using module file /home/lily/.local/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_container.py
<54.234.37.235> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<54.234.37.235> SSH: EXEC ssh -vvv -o ForwardAgent=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=30 54.234.37.235 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-gjqwsbtfwnmpqjodgvbvmakfnrceibbk; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''

this part takes forever

maybe it is this bit too?
Using module file /home/lily/.local/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_container.py

**Comment by lily-mayfield** [comment]
Relevant: #82

**Comment by lily-mayfield** [comment]
Okay @wearpants, updates only take me 1 minute and starting a cluster is like 5+ minutes faster for me when I tested. I hope this speed increase is reproducible for you :crossed_fingers:

Thanks! :smile: :heart:

**Comment by wearpants** [comment]
i think this is better now :-)
