### ISSUE TITLE
Deploy script doesn't need master ip

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-pipeline#102]
Deploy script can determine spark master ip from `ec2.py` because it's tagged with `spark_master_node` or something like that. At the end it should print this value out to the user, interpolated like: `http://masterip:8080/`

**Comment by wearpants** [comment]
Yes please!

**Comment by lily-mayfield** [comment]
Fixed in https://github.com/opensyllabus/osp-pipeline/releases/tag/v0.10.0
