### ISSUE TITLE
make all deploy scripts a single python script that uses docopt!

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-pipeline#103]
Might be easier than having like a billion gorillion files scattered spaghetti style from here to the cosmos (my bad!).

**Comment by SlimeMaid** [comment]
Relevant: #90 and #104

**Comment by lily-mayfield** [comment]
Relevant: #90 and #104

**Comment by lily-mayfield** [comment]
Fixed  in https://github.com/opensyllabus/osp-pipeline/releases/tag/v0.10.0
