### ISSUE TITLE
cluster.py should send state messages to #cluster-status slack channel

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-pipeline#111]
like `up <url>` and `down`

this is just pushing status to slack, not full blown chatops

**Comment by lily-mayfield** [comment]
I think this may be finished in #115 I just have to test it! :smiley:

**Comment by lily-mayfield** [comment]
Implemented in https://github.com/opensyllabus/osp-pipeline/releases/tag/v0.11.0

yay! was fun
