### ISSUE TITLE
Update spark to 2.2.1

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-pipeline#117]
I got this message after updating spark to `2.2.1`:

> Service 'dev' failed to build: The command '/bin/sh -c curl -sL --retry 3   "http://d3kbcqa49mib13.cloudfront.net/${SPARK_PACKAGE}.tgz"   | gunzip   | tar x -C /opt/  && mv /opt/$SPARK_PACKAGE $SPARK_HOME  && chown -R root:root $SPARK_HOME' returned a non-zero code: 2

See: https://travis-ci.org/opensyllabus/osp-pipeline/builds/325253905

**Comment by lily-mayfield** [comment]
I'm pretty sure https://github.com/opensyllabus/osp-pipeline/commit/bde9a5d1aa0b323c69db58d7d36eacc4a5b3c08a fixes this issue (see: https://travis-ci.org/opensyllabus/osp-pipeline/builds/325276737).

**Comment by wearpants** [comment]
getting this same error when i try to `push-image.sh` locally...

**Comment by wearpants** [comment]
this URL seems to work http://apache.osuosl.org/spark/spark-2.2.1/spark-2.2.1-bin-hadoop2.7.tgz

**Comment by lily-mayfield** [comment]
i changed it to http://apache.osuosl.org/spark/spark-2.2.1/

should work !!

I agree I think the value should just be hardcoded.

**Comment by lily-mayfield** [comment]
Offending line: https://github.com/opensyllabus/osp-pipeline/blob/master/Dockerfile#L69

**Comment by lily-mayfield** [comment]
I think this is fixed now? @wearpants

**Comment by wearpants** [comment]
yup thanks!
