### ISSUE TITLE
support local copies of shared repos

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-pipeline#129]
It's currently impossible to reference a locally modified copy of `osp-text-extractor` (and presumably other such git-referenced requirements) in a build of osp-pipeline's docker container, as would be expected with `pip install -e /path/to/osp-text-extractor/setup.py`. Instead, you have to commit & push to github, and update the hash in `requirements.txt`. This makes development hard & breaks expected behavior

**Comment by wearpants** [comment]
pete [4:19 PM]
@jody if i need to make change to both osp-text-extractor & osp-pipeline, how do i get the docker `build/run-tests.sh` to notice my local copy of osp-text-extractor?
[4:20 PM]
I tried the standard `pip install -e /path/to/osp-text-extractor` but it didn't work
[4:20 PM]
really wanted a single repo....

[4:23 PM]
@jody prompt answer appreciated, this is blocking me

jody [4:43 PM]
@pete Hmm, I think the problem with your command is that `build/run-tests.sh` doesn't actually do any updating of the docker build, it just logs into it and runs `pytest`.  So I think you would need to edit requirements.txt, then run `docker-compose build` again (which I think will go faster because little has changed).  You might also not want to run with `-e` since I think that just creates a linkage to the local path, which the container doesn't have access to.
[4:44 PM]
Alternatively, you could run `docker-compose run dev bash` to get into the shell in the container, `pip install` from some source in there, and then run `pytest` yourself. (edited)
[4:45 PM]
If you've pushed a branch to the repo or something, that's probably easiest.

pete [4:48 PM]
ugh, so i have to push a commit to github to test it locally?
[4:48 PM]
that's... suboptimal

jody [4:57 PM]
Well, you don't have to push to master, necessarily.  You can push to a development branch and `pip install` from that, or you could possibly have a local `pip install -e git+https://<url>` copy that you work out of

pete [5:06 PM]
still gotta push to github :disappointed:

**Comment by wearpants** [comment]
@jodizzle this is on you, with help as needed from @lily-mayfield

**Comment by jody** [comment]
Hi there!  Did you intend to include me in this discussion, or was that an error?

**Comment by jodizzle** [comment]
@jody Copy paste error by @wearpants.  Sorry about that!

I'll edit the comment above.

**Comment by pete** [comment]
@jody My strategy when this occurs is to try to reply sincerely, presupposing it was intentional. (I was thinking of insisting that I had said none of those things and feigning insult at the suggestion that I would use an emoji.)

**Comment by jodizzle** [comment]
@pete @jody I'm gonna go ahead and close this issue and open a new one so that you two don't keep getting pinged.  Thanks for stopping by :)
