### ISSUE TITLE
Memory issues, add swap

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-pipeline#137]
Reading material:

  * https://tecadmin.net/add-swap-partition-on-ec2-linux-instance/
  * https://stackoverflow.com/questions/17173972/how-do-you-add-swap-to-an-ec2-instance
  * https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-store-swap-volumes.html

**Comment by wearpants** [comment]
no longer needed
