### ISSUE TITLE
More bigger disk for spark

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-pipeline#149]
Running out of disk space again... current root volume is 100GB, let's try 500GB (unless there's a reason not to, in which case we can find something in the middle)

```
ubuntu@ip-10-0-0-237:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       99G   99G     0 100% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            241G   12K  241G   1% /dev
tmpfs            49G  388K   49G   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            241G  344K  241G   1% /run/shm
none            100M     0  100M   0% /run/user
```

this is for `/mnt/spark` (currently on root volume)

**Comment by lily-mayfield** [comment]
Okay should be fixed? https://github.com/opensyllabus/osp-pipeline/blob/master/deploy/roles/ec2-instance/tasks/main.yml#L29

**Comment by lily-mayfield** [comment]
Raised to 2TB https://github.com/opensyllabus/osp-pipeline/commit/b6ffb55977aecf6b6a197ce7cecb29919acc29dc
