### ISSUE TITLE
Patch daemon.py with Ansible

### ISSUE THREAD

**Issue by davidmcclure** [opensyllabus/osp-pipeline#16]
@wearpants, do we need to update `daemon.py` both in `/opt/spark/python/pyspark` and in `/opt/spark/python/lib/pyspark.zip`? What's the difference between the two?

**Comment by wearpants** [comment]
For testing? Yes both

**Comment by davidmcclure** [comment]
Circling back to this - is it necessary to do this in 2.1.1? I notice that I haven't re-applied the patch since upgrading, I'm getting good coverage reports.

**Comment by wearpants** [comment]
Yes it is

**Comment by davidmcclure** [comment]
My memory is fuzzy on this - the patch was necessary to get coverage in files that import from pyspark, is that right? I'm seeing non-0 coverages for the corpus jobs though, without the patch, so it seems like it might be working out of the box?

**Comment by wearpants** [comment]
Yes, but those coverage reports are not correct. There is this will not
work out of the box, the daemon.py file did not change in the new version.

**Comment by lily-mayfield** [comment]
Is this something that I should just have Docker do automatically?

**Comment by wearpants** [comment]
Yeah somewhere it's needed for correct coverage reports

**Comment by lily-mayfield** [comment]
Okay, great; I'm having some issues in #72 but I'm sure I can iron them out this weekend...

**Comment by davidmcclure** [comment]
Can we confirm that this is still necessary? If so, can we submit the change as a PR to pyspark?

It feels sloppy to manually patch the local installation of the pyspark source, and adds complexity to the build.

**Comment by wearpants** [comment]
The answer is still yes, it is necessary for correct coverage. Nothing has
changed in our stack here.

It's not a small amount of work to generalize, document, test, etc. this
code for submitting upstream  and it would be several months until it was
in a production Spark release.
