### ISSUE TITLE
Add support for Rich Text Format

### ISSUE THREAD

**Issue by jodizzle** [opensyllabus/osp-pipeline#31]
There are a couple sites that I've come across that have syllabi available in RTF.  It would be nice if these types of files could be handled by the pipeline.

**Comment by wearpants** [comment]
Do you want to try to take a crack at this? You'd add a `rtf_to_text function here: https://github.com/opensyllabus/osp-pipeline/blob/master/osp_pipeline/corpus/utils.py#L43
and then wire it throughout in a similar manner

**Comment by jodizzle** [comment]
Sure, I'll give it a shot.

**Comment by jodizzle** [comment]
Resolved in https://github.com/opensyllabus/osp-pipeline/pull/34.
