### ISSUE TITLE
Automate Spark install / patching

### ISSUE THREAD

**Issue by davidmcclure** [opensyllabus/osp-pipeline#5]
Thinking about getting new contributors up and running -- I wonder if we could automate the process of downloading spark, patching in the jars, patching the daemon.py file, etc?

If this gets complicated enough, it might make sense to do this under Vagrant with Ansible, but for now maybe just a `./bin/setup-dev` script?

**Comment by wearpants** [comment]
Re: downloading jars - this would be better addressed by #6

**Comment by davidmcclure** [comment]
This is in place on the feature/spark branch of `osp-deploy`. The only missing thing is the pyspark patch to get the test coverage working. @wearpants Did you submit an issue to pyspark about that? It would be nice if we didn't have to maintain that patch in our repo.

**Comment by wearpants** [comment]
I haven't submitted a patch, as I'm not 100% sure it's done "right", or how to write a test case for it. It'd be a bit of work & back-and-forth to get this accepted by Spark, not sure if we want to do that right now? (though it would be useful to other folks as well).

**Comment by davidmcclure** [comment]
Yeah, probably not worth it.
