### ISSUE TITLE
nitpick: delete docker-tests.sh and just update pytests.ini

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-pipeline#66]
`docker-tests.sh` is only being used to store options which is done more conventionally by `pytests.ini`, which we already have. I think it'd be nice to move those options to the `pytest.ini` file in the name of centralizing all the `pytest` options to one place.

**Comment by wearpants** [comment]
Sounds good

**Comment by lily-mayfield** [comment]
Fixed in https://github.com/opensyllabus/osp-pipeline/commit/1724a936dc18a4602a3c0bd44f4f7f5ead05d523
