### ISSUE TITLE
Clean out unused branches

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-pipeline#71]
There's a ton of branches, are any of them unused? If so it would be good to delete them.

**Comment by wearpants** [comment]
Will confirm what I'm still using, but yes

**Comment by davidmcclure** [comment]
Agreed, I'll get rid of my old branches.

**Comment by wearpants** [comment]
done

**Comment by lily-mayfield** [comment]
Thank you so much @wearpants and @davidmcclure! I really appreciate it! :smile:

**Comment by davidmcclure** [comment]
I haven't gotten rid of mine yet, reopening until I do.

**Comment by davidmcclure** [comment]
Done.
