### ISSUE TITLE
Is it okay to expose vault key?

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-pipeline#78]
@jodizzle and I were wondering about the vault key, if it's okay to expose it like it is.

Sorry for the poorly written issue, I am likely going to be getting around to addressing this myself ASAP, but just documenting here just in case.

I've assigned those concerned.

Thanks!

**Comment by davidmcclure** [comment]
This is safe, though I also don't love it. A couple considerations:

- This is basically what tools like Vault are designed for - a way to commit secrets into repositories in a safe way. The file can't be decrypted without the vault password, which isn't included in the repository. Arguably, though, this adds surface area for mistakes if, eg, the password file ever got accidentally committed.

- Right now nothing actually sensitive is included in the file - just ids of EC2 resources (eg, the subnet id), which I think would actually be fine to store as clear-text in the repo. Though, going forward, we might need to include real secrets, like AWS credentials.

- The advantage to including the vault file is that the repo is totally self-contained - a developer can just clone the repo, get the vault password, and everything just works. If the vault file(s) is omitted, then we've got a set of YAML files that need to get passed around behind-the-scenes, which can get gnarly.

I wonder, out of an abundance of caution - would it work to put the vault files in a private repo, and then include that as a submodule in the pipeline, sort of like what we do with the fixtures?

**Comment by lily-mayfield** [comment]
Thank you so much @davidmcclure !! This is such good information! I appreciate it!
