### ISSUE TITLE
Confirm success of removal of Docker Hub

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-pipeline#79]
Docker Hub was removed for security (I took care of this; nothing big, I looked through logs) and dramatic speed reduction purposes, and as far as I can tell Docker Hub isn't needed for production (I know it isn't for testing because tests pass).

Here are some of the lines I noticed for production in Ansible which needs Docker name and image:

  * Defined in: https://github.com/opensyllabus/osp-pipeline/blob/ef8ca513bf258dcb58ead88c5b5296c22db03c9c/deploy/ansible/roles/spark/defaults/main.yml
  * Used in: https://github.com/opensyllabus/osp-pipeline/blob/ef8ca513bf258dcb58ead88c5b5296c22db03c9c/deploy/ansible/roles/spark/tasks/start.yml

I think simply setting the container name and built image name in `docker-compose.yml` solves any issues, but say the docker instances being spun up can't access the built image, then we will need to push to ECS repo on `master` pushes, and only use said image in production.

**Comment by davidmcclure** [comment]
Hey @lily-mayfield,

Can you say more about this - where was it removed? We do need to push to Docker Hub for deployment, with the current system - the image has to be available on some kind of public-facing registry so that the EC2 nodes can pull it when the cluster is deployed.

**Comment by lily-mayfield** [comment]
@davidmcclure I went ahead and got a micro subscription to docker hub for private repo. i'll add back instructions for manually updating the image and all that.

thanks!

**Comment by lily-mayfield** [comment]
Also sorry about that--I totally spaced on this one!
