### ISSUE TITLE
gather spark logs

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-pipeline#91]
using the scripts imported from the old `osp-deploy` repo in https://github.com/opensyllabus/osp-pipeline/commit/4b5625d47989be73232fbcd41b01404f1b2f1d3a wire it up to work with our new docker deploy

If we can expose the docker image to the host, this should almost work out of the box: https://docs.docker.com/engine/admin/volumes/volumes/

**Comment by wearpants** [comment]
The difficulty is that the the playbook expects to find the logs in the host, rather than the container, but still in the `/opt/spark-2.2.0/work/` directory

**Comment by davidmcclure** [comment]
Quick idea with this - we mount the `/mnt` directory from the host into the Docker container, which is then used as the Spark scratch disk. I'd have to dig around in the Spark config docs, but I bet we could set a custom logging directory? If so, we could just put it in something like `/mnt/spark-logs`, and then anything that gets written from the container would be visible to the host.

**Comment by lily-mayfield** [comment]
I believe this is fixed in v0.9.0
