### ISSUE TITLE
Switch to c3.8xlarge as the default instance type

### ISSUE THREAD

**Issue by davidmcclure** [opensyllabus/osp-pipeline#92]
I've been doing this in other projects, and noticed that we're still using the c4's here. The c3.8xlarge's have 4 fewer cores (32 instead of 36), but the advantage is that they have large SSD's, which we can use as scratch space for Spark. This is faster than writing spill-over data onto EBS, and also avoids memory problems if the jobs fill up the (small) root volumes on the workers.

**Comment by wearpants** [comment]
fixed
