### ISSUE TITLE
Spark JVM Memory tuning

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-pipeline#97]
We're getting OOM'd on workers because of excessive memory usage. By default, spark uses `total RAM - 1GB`; on a `c3.8xlarge`, it computes this as `51200M` for the worker. This doesn't leave enough for python processes/OS. Take this down to `47200M` by setting the `SPARK_WORKER_MEMORY` environment variable, as [documented here](http://spark.apache.org/docs/latest/spark-standalone.html#cluster-launch-scripts)

**Comment by wearpants** [comment]
Not sure if that's enough, we'll see

**Comment by lily-mayfield** [comment]
Okay, I'll get on this right now!

**Comment by lily-mayfield** [comment]
@wearpants okay check it out! Please let me know if this works and I'll close this issue. :) Thanks!

https://github.com/opensyllabus/osp-pipeline/commit/83f9d1f92abe7c17a4a80db021934eb73c6638d8

**Comment by wearpants** [comment]
Yeah lets doument. Actual value Should probably live in same place we set instance type& number of nodes, and then propogate through Ansible variable

**Comment by lily-mayfield** [comment]
Uh oh having some issues but we're getting to the bottom of it...

**Comment by wearpants** [comment]
Should probably revert or comment out in light of #99

**Comment by wearpants** [comment]
eh, let's leave it, a little free ram won't hurt
